name: CI/CD using Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Application
        run: mvn clean package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Push Artifact to S3
        run: aws s3 cp target/*.war s3://priyanka.space/student.war
      - name: Docker Build 
        run: | 
          docker build -t student . 
          docker images
      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 344530146939.dkr.ecr.ap-south-1.amazonaws.com
          docker tag student:latest 344530146939.dkr.ecr.ap-south-1.amazonaws.com/student:latest
          docker push 344530146939.dkr.ecr.ap-south-1.amazonaws.com/student:latest
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt 
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply 
        run: terraform apply -auto-approve 
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure EKS cluster 
        run: aws eks update-kubeconfig --name my-eks-cluster --region ap-south-1
          
      - name: Deployment On kubernetes
        run: |
         kubectl apply -f k8s/
         sleep 30
         kubectl get pods 
         kubectl get svc -o wide  
